# Generated by Django 5.2.8 on 2025-11-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsmind', '0003_profile_readhistory_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
