# Generated by Django 5.2.8 on 2025-11-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsmind', '0004_customuser_avatar_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
