# Generated by Django 5.2.8 on 2025-11-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsmind', '0005_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
