# Generated by Django 5.2.8 on 2026-01-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsmind', '0006_remove_customuser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadHistory',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
